# Generated by Django 2.0 on 2021-03-16 08:57

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0002_auto_20210316_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npi', models.CharField(max_length=10, null=True)),
                ('symptoms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=None, help_text='symptoms in the order of preference', null=True, size=None)),
                ('specialization', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), default=None, help_text='specialization in the order of preference', null=True, size=None)),
                ('undergraduate_degree', models.CharField(max_length=30, null=True)),
                ('postgraduate_degree', models.CharField(max_length=30, null=True)),
                ('photo_url', models.URLField(default=None, help_text='An optional image of the user', null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('alternate_phone', models.CharField(max_length=15, null=True)),
                ('preferred_languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=None, help_text='Language codes of preferred languages in the order of preference', null=True, size=None)),
                ('address', models.TextField(null=True)),
                ('city', models.CharField(default=None, max_length=20, null=True)),
                ('country_of_origin', models.CharField(default=None, max_length=20, null=True)),
                ('country', models.CharField(default=None, max_length=20, null=True)),
                ('contacts', models.ManyToManyField(default=None, help_text='Users a user has contact on this platform', related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
