# Generated by Django 2.0 on 2021-03-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('D', 'Doctor'), ('P', 'Patient')], default=None, max_length=10, null=True),
        ),
    ]
