# Generated by Django 2.0 on 2021-03-24 07:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0005_auto_20210316_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='specialization',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=None, help_text='specialization in the order of preference', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='symptoms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=None, help_text='symptoms in the order of preference', null=True, size=None),
        ),
    ]
