# Generated by Django 2.0 on 2020-09-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='sequence',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
